### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jtlindsey** [rajayogan/angular2-desktop#1]
Hello, I'm new to angular and found your video helpful for getting started with angular and electron. Most of the toutorials I see about angular are using a different syntax. How do i get this to work in this app?

```
    <div ng-app="">

    <p>Input something in the input box:</p>
    <p>Name : <input type="text" ng-model="name" placeholder="Enter name here"></p>
    <h1>Hello {{name}}</h1>

    </div>

```

Right now hello {{name}} just return plain text when place in index.html

example from 
http://www.w3schools.com/angular/tryit.asp?filename=try_ng_default

**Comment by rajayogan** [comment]
Uhmm.. Okay. The example which you have provided is written using Angular 1.x framework whereas the repos I submit are written using Angular 2 + Typescript framework. Angular 2 is the newer version of Angular bro and there are huge migration projects going on from Angular 1 to Angular 2 (Even though Angular 2 is not yet stable). If you are starting out new, I would suggest you to start with Angular 2. Thanks. Have a nice day.
